// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDciCpyNqxN7AHLrxUg0MEC5UcpQlbZAUk',
    appId: '1:934540926934:web:0828b0d5ae4f1f62858e77',
    messagingSenderId: '934540926934',
    projectId: 'watermind-d4485',
    authDomain: 'watermind-d4485.firebaseapp.com',
    storageBucket: 'watermind-d4485.firebasestorage.app',
    measurementId: 'G-FXPRDPR9N2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXAUqWpsNnicjHeQSZGjAiNUJnx_DX2yU',
    appId: '1:934540926934:android:f241cdbaa8be9e16858e77',
    messagingSenderId: '934540926934',
    projectId: 'watermind-d4485',
    storageBucket: 'watermind-d4485.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9w30lEqqnnU-9Zn_wZZjMFPdp_HAyAZU',
    appId: '1:934540926934:ios:d0387c77c387acd6858e77',
    messagingSenderId: '934540926934',
    projectId: 'watermind-d4485',
    storageBucket: 'watermind-d4485.firebasestorage.app',
    iosBundleId: 'com.example.watermind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9w30lEqqnnU-9Zn_wZZjMFPdp_HAyAZU',
    appId: '1:934540926934:ios:d0387c77c387acd6858e77',
    messagingSenderId: '934540926934',
    projectId: 'watermind-d4485',
    storageBucket: 'watermind-d4485.firebasestorage.app',
    iosBundleId: 'com.example.watermind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDciCpyNqxN7AHLrxUg0MEC5UcpQlbZAUk',
    appId: '1:934540926934:web:748ae4c46d698be4858e77',
    messagingSenderId: '934540926934',
    projectId: 'watermind-d4485',
    authDomain: 'watermind-d4485.firebaseapp.com',
    storageBucket: 'watermind-d4485.firebasestorage.app',
    measurementId: 'G-9DWDL46JG4',
  );
}
